import pptxgen from 'pptxgenjs';
import { Presentation } from 'lucide-react';
import { type GeneratedContent } from '../lib/gemini';

interface Props {
    content: GeneratedContent;
}

export function PPTGenerator({ content }: Props) {

    const generatePPT = async () => {
        const pres = new pptxgen();
        pres.layout = 'LAYOUT_16x9';

        // Theme based on temp_ppt/sample.pptx analysis
        const theme = {
            colors: {
                primary: '1F497D',   // Extracted Dark Blue
                secondary: '4F81BD', // Extracted Lighter Blue
                accent: 'C0504D',    // Extracted Red/Brown Accent
                text: '333333',
                lightBg: 'EEECE1',   // Extracted Beige/Light Background
                white: 'FFFFFF'
            }
        };

        // Define Slide Master for consistent design
        pres.defineSlideMaster({
            title: "MASTER_SLIDE",
            background: { color: theme.colors.lightBg },
            objects: [
                // Header Bar (Primary Color)
                { rect: { x: 0, y: 0, w: '100%', h: 1.0, fill: { color: theme.colors.primary } } },
                // Decorative Line (Secondary Color)
                { rect: { x: 0, y: 1.0, w: '100%', h: 0.1, fill: { color: theme.colors.secondary } } },
                // Footer Bar
                { rect: { x: 0, y: '92%', w: '100%', h: 0.8, fill: { color: "E0E0E0" } } },
                // Footer Text
                { text: { text: "Portfolio Generated by PortfolioAI", options: { x: 0.5, y: '95%', fontSize: 10, color: '666666' } } }
            ],
            // Slide Numbers
            slideNumber: { x: '95%', y: '95%', fontFace: 'Arial', fontSize: 10, color: '666666' }
        });

        // Helper to add typical title
        const addSlideWithTitle = (title: string) => {
            const slide = pres.addSlide({ masterName: "MASTER_SLIDE" });
            // Title text on the header
            slide.addText(title, {
                x: 0.5, y: 0.25, w: '90%', h: 0.6,
                fontSize: 28, bold: true, color: theme.colors.white, align: 'left', fontFace: 'Arial'
            });
            return slide;
        };

        // --- Slide 1: Cover ---
        const coverSlide = pres.addSlide();
        coverSlide.background = { color: theme.colors.white };

        // Add decorative lines from sample (image2.png positions)
        coverSlide.addImage({
            path: '/ppt_assets/image2.png',
            x: 0.5, y: 0.1, w: 9.0, h: 0.01
        });
        coverSlide.addImage({
            path: '/ppt_assets/image2.png',
            x: 0.5, y: 5.0, w: 9.0, h: 0.01
        });

        // Main Title
        coverSlide.addText("PORTFOLIO", {
            x: 0.5, y: 1.0, w: '90%', fontSize: 80, bold: true, color: '000000', align: 'left', fontFace: 'Arial'
        });

        // Subtitle with accent
        coverSlide.addText("맞춤형 포트폴리오 제안", {
            x: 0.5, y: 2.5, w: '90%', fontSize: 36, bold: true, color: theme.colors.text, align: 'left', fontFace: 'Arial'
        });

        // Decorative icons (image1.png, image6.png)
        coverSlide.addImage({
            path: '/ppt_assets/image6.png',
            x: 8.5, y: 3.5, w: 0.8, h: 0.8
        });

        // --- Slide 2: Introduction ---
        let slide = addSlideWithTitle("자기 소개 (Introduction)");

        // Add decorative element
        slide.addImage({
            path: '/ppt_assets/image9.png',
            x: 0.3, y: 1.5, w: 0.3, h: 0.3
        });

        slide.addText(content.intro, {
            x: 0.8, y: 1.5, w: '85%', h: 4.5,
            fontSize: 16, color: theme.colors.text,
            align: 'left', valign: 'top',
            lineSpacing: 22, fontFace: 'Arial'
        });

        // --- Slide 3+: Key Matches (Pagination Logic) ---
        const ITEMS_PER_SLIDE = 3;
        const matchesChunks = [];
        for (let i = 0; i < content.keyMatches.length; i += ITEMS_PER_SLIDE) {
            matchesChunks.push(content.keyMatches.slice(i, i + ITEMS_PER_SLIDE));
        }

        matchesChunks.forEach((chunk, chunkIndex) => {
            const s = addSlideWithTitle(chunkIndex === 0 ? "주요 핵심 역량 (Key Matches)" : "주요 핵심 역량 (Continued)");

            // Add decorative background image
            s.addImage({
                path: '/ppt_assets/image12.png',
                x: 7.5, y: 2.0, w: 2.0, h: 2.0,
                transparency: 30
            });

            chunk.forEach((match, index) => {
                const yPos = 1.5 + (index * 1.8);

                // Add icon for each item
                s.addImage({
                    path: '/ppt_assets/image10.png',
                    x: 0.3, y: yPos, w: 0.15, h: 0.15
                });

                // Skill Title
                s.addText(match.skill, {
                    x: 0.6, y: yPos, w: '85%', h: 0.4,
                    fontSize: 20, bold: true, color: theme.colors.primary
                });
                // Evidence
                s.addText(match.evidence, {
                    x: 0.8, y: yPos + 0.5, w: '80%', h: 1.0,
                    fontSize: 16, color: theme.colors.text
                });
            });
        });

        // --- Gap Analysis (Pagination) ---
        if (content.gapAnalysis && content.gapAnalysis.missingSkills.length > 0) {
            const missingChunks = [];
            for (let i = 0; i < content.gapAnalysis.missingSkills.length; i += ITEMS_PER_SLIDE) {
                missingChunks.push(content.gapAnalysis.missingSkills.slice(i, i + ITEMS_PER_SLIDE));
            }

            missingChunks.forEach((chunk, chunkIndex) => {
                const s = addSlideWithTitle(chunkIndex === 0 ? "역량 강화 계획 (Gap Analysis)" : "역량 강화 계획 (Continued)");

                // Add decorative elements
                s.addImage({
                    path: '/ppt_assets/image13.png',
                    x: 0.3, y: 1.3, w: 0.2, h: 0.2
                });

                chunk.forEach((gap, index) => {
                    const yPos = 1.5 + (index * 1.8);

                    // Warning icon
                    s.addImage({
                        path: '/ppt_assets/image14.png',
                        x: 0.3, y: yPos, w: 0.15, h: 0.15
                    });

                    s.addText(gap.skill, {
                        x: 0.6, y: yPos, w: '85%', h: 0.4,
                        fontSize: 20, bold: true, color: theme.colors.accent
                    });
                    s.addText(`추천 활동: ${gap.recommendation}`, {
                        x: 0.8, y: yPos + 0.5, w: '80%', h: 1.0,
                        fontSize: 16, color: theme.colors.text, italic: true
                    });
                });
            });

            // Advice Slide
            const advSlide = addSlideWithTitle("전문가 조언 (Professional Advice)");

            // Add chart/graph images from sample
            advSlide.addImage({
                path: '/ppt_assets/image25.png',
                x: 7.0, y: 2.0, w: 2.5, h: 2.0,
                transparency: 20
            });

            advSlide.addText(content.gapAnalysis.advice, {
                x: 0.5, y: 1.5, w: '60%', h: 4.5,
                fontSize: 18, color: theme.colors.text, lineSpacing: 24, fontFace: 'Arial'
            });
        }

        // --- Cover Letter ---
        const clSlide = addSlideWithTitle("커버 레터 (Cover Letter)");

        // Add paper background shape
        clSlide.addShape(pres.ShapeType.rect, {
            x: 0.4, y: 1.4, w: '92%', h: 5.0,
            fill: { color: theme.colors.white },
            line: { color: 'CCCCCC', width: 1 }
        });

        // Add decorative corner element
        clSlide.addImage({
            path: '/ppt_assets/image29.png',
            x: 8.5, y: 1.5, w: 0.4, h: 0.4
        });

        clSlide.addText(content.coverLetter, {
            x: 0.6, y: 1.6, w: '88%', h: 4.6,
            fontSize: 12, color: theme.colors.text,
            align: 'justify', valign: 'top'
        });

        // --- Last Slide: Thank You ---
        const endSlide = pres.addSlide();
        endSlide.background = { color: theme.colors.white };

        // Add decorative lines (similar to cover)
        endSlide.addImage({
            path: '/ppt_assets/image2.png',
            x: 0.5, y: 2.0, w: 9.0, h: 0.01
        });
        endSlide.addImage({
            path: '/ppt_assets/image2.png',
            x: 0.5, y: 4.5, w: 9.0, h: 0.01
        });

        // Add decorative icons from slide 7
        endSlide.addImage({
            path: '/ppt_assets/image4.png',
            x: 1.0, y: 3.0, w: 0.3, h: 0.3
        });
        endSlide.addImage({
            path: '/ppt_assets/image5.png',
            x: 8.5, y: 3.0, w: 0.3, h: 0.3
        });

        endSlide.addText("감사합니다", {
            x: 0, y: 2.5, w: '100%', fontSize: 50, bold: true, color: '000000', align: 'center', fontFace: 'Arial'
        });
        endSlide.addText("THANK YOU", {
            x: 0, y: 3.5, w: '100%', fontSize: 30, color: theme.colors.secondary, align: 'center', fontFace: 'Arial'
        });

        await pres.writeFile({ fileName: "Tailored_Portfolio.pptx" });
    };

    return (
        <button
            onClick={generatePPT}
            className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white rounded-lg transition-all font-medium shadow-md hover:shadow-lg active:scale-95"
        >
            <Presentation size={18} />
            <span>PPT 다운로드</span>
        </button>
    );
}
